package erro

var (
	Succ               = NewError(0, "succ")
	ErrInvalid         = NewError(-1, "Invalid")
	ErrServerStopped   = NewError(-2, "gobbq: the server has been stopped")
	ErrNoServive       = NewError(-3, "gobbq: no register service")
	ErrServerUnknown   = NewError(-4, "gobbq: the network is unknown")
	ErrUnknownClient   = NewError(-5, "unknown client")
	ErrBadContext      = NewError(-6, "bad context")
	ErrContextDone     = NewError(-7, "context done")
	ErrTimeOut         = NewError(-8, "time out")
	ErrBadCall         = NewError(-9, "bad call, no dst entity")
	ErrBadResponse     = NewError(-10, "unknown response")
	ErrMethodNameError = NewError(-11, "mothod name error")
	ErrMethodNotFound  = NewError(-12, "mothod not found")
	ErrServiceNotFound = NewError(-13, "service not found")
	ErrEntityNotFound  = NewError(-14, "entity not found")
	ErrUnknownCallType = NewError(-15, "unknown call type")
	ErrEmptyEntityID   = NewError(-16, "bad call, empty dst entity")
	ErrBadRequest      = NewError(-17, "bad call, nil parameters")
	ErrConClosed       = NewError(-18, "conn closed")
	ErrConBlocking     = NewError(-18, "conn blocking")
)
