name: Build

on: [ pull_request ]

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-20.04
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        if: "github.ref != 'refs/heads/master'"

  build:
    name: Build (Go ${{ matrix.go }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [1.17, 1.18]
        os: ["ubuntu-20.04", "macos-11"]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v2
      - name: Build
        run: |
          go mod tidy
          go install ./cmd/...
          gobbq build examples/nil_game
          gobbq build examples/test_game
          gobbq build examples/test_client
          gobbq build examples/chatroom_demo
          gobbq build examples/unity_demo
